version: "3.9"
services:
  postgres-database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=lagranzanahoriavendra
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tasks-book-network

  app-image:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres-database
    networks:
      - tasks-book-network

volumes:
  postgres-data:

networks:
  tasks-book-network:
